{
 "title": "Availability - Performance - Quality for Broken Review Endpoint",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Errors Broken Get Review",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "rate(error_on_return_review_broken_count_total[5m])"
    }
   ]
  },
  {
   "title": "Time to Get Review Broken",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "bookstore_review_get_review_broken_time_seconds_max"
    }
   ]
  },
  {
   "title": "Broken Review Rated[5m]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(bookstore_review_get_review_broken_count_total[5m])"
    }
   ]
  },
  {
   "title": "Alerts panel",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  }
 ]
}