{
 "title": "Reviews Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Add Review",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Add Review rated [5m]",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(bookstore_review_add_review_count_total[5m])"
      }
     ]
    },
    {
     "title": "Add Review Counter",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bookstore_review_add_review_count_total"
      }
     ]
    },
    {
     "title": "Add Review Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "bookstore_review_get_reviews_time_seconds_max"
      }
     ]
    }
   ]
  },
  {
   "title": "Update Review",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Update Review rated [5m]",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(bookstore_review_update_review_count_total[5m])"
      }
     ]
    },
    {
     "title": "Update Review Counter",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bookstore_review_update_review_count_total"
      }
     ]
    },
    {
     "title": "Update Review Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "bookstore_review_update_review_time_seconds_max"
      }
     ]
    }
   ]
  },
  {
   "title": "Delete Review",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Review rated [5m]",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(bookstore_review_delete_review_count_total[5m])"
      }
     ]
    },
    {
     "title": "Delete Review Counter",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bookstore_review_delete_review_count_total"
      }
     ]
    },
    {
     "title": "Delete Review Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "bookstore_review_delete_review_time_seconds_max"
      }
     ]
    }
   ]
  },
  { "title": "Get review", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Get Review rated [5m]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(bookstore_review_get_review_count_total[5m])"
    }
   ]
  },
  {
   "title": "Get Review Counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bookstore_review_get_review_count_total"
    }
   ]
  },
  {
   "title": "Get Review Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "bookstore_review_get_review_time_seconds_max"
    }
   ]
  },
  { "title": "Get Reviews", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Get Reviews rated [5m]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(bookstore_review_get_reviews_count_total[5m])"
    }
   ]
  },
  {
   "title": "Get Reviews Counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bookstore_review_get_reviews_count_total"
    }
   ]
  },
  {
   "title": "Get Reviews Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "bookstore_review_get_reviews_time_seconds_max"
    }
   ]
  },
  { "title": "Get Book Reviews", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Get Book Reviews rated [5m]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(bookstore_review_get_book_reviews_count_total[5m])"
    }
   ]
  },
  {
   "title": "Get Book Reviews Counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bookstore_review_get_book_reviews_count_total"
    }
   ]
  },
  {
   "title": "Get Book Reviews Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "bookstore_review_get_book_reviews_time_seconds_max"
    }
   ]
  },
  { "title": "Get User Reviews", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Get User Reviews rated [5m]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(bookstore_review_get_user_reviews_count_total[5m])"
    }
   ]
  },
  {
   "title": "Get User Reviews Counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bookstore_review_get_user_reviews_count_total"
    }
   ]
  },
  {
   "title": "Get User Reviews Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "bookstore_review_get_user_reviews_time_seconds_max"
    }
   ]
  }
 ]
}